/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan1
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulir = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        kelas1 = new javax.swing.JLabel();
        alamat1 = new javax.swing.JLabel();
        isinama1 = new javax.swing.JTextField();
        isikelas1 = new javax.swing.JTextField();
        isialamat1 = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        nama2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kelas2 = new javax.swing.JLabel();
        alamat2 = new javax.swing.JLabel();
        isinama2 = new javax.swing.JTextField();
        isikelas2 = new javax.swing.JTextField();
        isialamat2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        formulir.setText("Formulir");
        getContentPane().add(formulir);
        formulir.setBounds(117, 9, 100, 39);

        nama1.setText("Nama");
        getContentPane().add(nama1);
        nama1.setBounds(15, 64, 41, 20);

        kelas1.setText("Kelas");
        getContentPane().add(kelas1);
        kelas1.setBounds(15, 99, 36, 20);

        alamat1.setText("Alamat");
        getContentPane().add(alamat1);
        alamat1.setBounds(15, 134, 50, 20);

        isinama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isinama1ActionPerformed(evt);
            }
        });
        getContentPane().add(isinama1);
        isinama1.setBounds(117, 64, 174, 26);
        getContentPane().add(isikelas1);
        isikelas1.setBounds(117, 99, 174, 26);
        getContentPane().add(isialamat1);
        isialamat1.setBounds(117, 134, 174, 26);

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(117, 191, 79, 29);

        nama2.setText("Nama ");
        getContentPane().add(nama2);
        nama2.setBounds(20, 240, 46, 20);

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(15, 64, 41, 20);

        jLabel7.setText("Nama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(15, 64, 41, 20);

        jLabel8.setText("Nama");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(15, 64, 41, 20);

        kelas2.setText("Kelas");
        getContentPane().add(kelas2);
        kelas2.setBounds(20, 280, 51, 20);

        alamat2.setText("Alamat");
        getContentPane().add(alamat2);
        alamat2.setBounds(20, 320, 50, 20);
        getContentPane().add(isinama2);
        isinama2.setBounds(120, 240, 170, 26);

        isikelas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isikelas2ActionPerformed(evt);
            }
        });
        getContentPane().add(isikelas2);
        isikelas2.setBounds(120, 280, 170, 26);
        getContentPane().add(isialamat2);
        isialamat2.setBounds(120, 320, 170, 26);

        setBounds(0, 0, 351, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void isinama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isinama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isinama1ActionPerformed

    private void isikelas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isikelas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isikelas2ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String nama = isinama1.getText();
        isinama2.setText(nama);
        String kelas = isikelas1.getText();
        isikelas2.setText(kelas);
        String alamat = isialamat1.getText();
        isialamat2.setText(alamat);
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat1;
    private javax.swing.JLabel alamat2;
    private javax.swing.JLabel formulir;
    private javax.swing.JTextField isialamat1;
    private javax.swing.JTextField isialamat2;
    private javax.swing.JTextField isikelas1;
    private javax.swing.JTextField isikelas2;
    private javax.swing.JTextField isinama1;
    private javax.swing.JTextField isinama2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel kelas1;
    private javax.swing.JLabel kelas2;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
